### PR TITLE
(#281) Allow running the client on windows

### PR DESCRIPTION
**Pull request by smortex**
This PR make choria look after the proper client configuration file on windows.

<details>
<summary>Details from a now fixed issue, see linked PR</summary>
For now, this only change the class error returned to the user from:

```
Could not configure Choria: ping failed to configure: could not parse configuration: open /etc/puppetlabs/mcollective/client.cfg: The system cannot find the path specified.
```

to:

```
Could not configure Choria: ping failed to configure: could not parse configuration: open C:\\ProgramData\\choria\\etc\\client.conf: Access is denied.
```

I am a bit clue-less with windows files permissions…  Opening a PR anyway so that people can find it and maybe provide hints to fix this issue!
</details>

### CODE REVIEW

**Comment by smortex** [comment]
Current status:

1. `choria enroll` wants to generate a certificate matching the node FQDN and not `%USERNAME%.mcollecive` as it does on other systems.  I worked around this issue by passing `--certname foo.mcollective` to `choria enroll`;  Because of this, I also had to `set MCOLLECTIVE_CERTNAME=foo.mcollective` for the rest of my tests;
2. `choria ping` worked as expected \o/
3. `choria req service status foo -C profile::foo` resulted in a lot of errors (exceptions I think but I lost this output) mixed with the expected output and unhandled ANSI escape sequences, so the terminal output with mixed stderr and stdout was hardly readable;
4. `choria req service status foo -C profile::foo` a second time resulted in the expected output and behavior :shrug: 

The progress-bar cause the screen to be cleared (that's why I lost the error messages), and the ANSI escape sequence for output coloring are not being handled by windows terminal, so this is a bit annoying but basically usable, which is good!

I think the point 1 above must be fixed (I would like to add it to this PR).  Maybe 3 was a fluke or bug in some SSL code path (I saw a quite a lot of segfaults when doing my various tests when asking for a certificate… probably missing files, but I could not determine the exact cause).  The rest is mostly cosmetic, so i think I will not handle it as part of this PR.

I'll continue to work on this next week…

**Comment by smortex** [comment]
Point 1 fixed in new commit.  I think it starts to be good for reviewing, I will be able to continue working on this next week.

**Comment by ripienaar** [comment]
Thanks a lot for this. Will need issues I suspect some of these will result in a lot of work 

We do have a setting to disable color I probably should honour that and default to off on windows. Though I was under the impression my color lib supported windows. What terminal did you use? Suspect much more success on the new one

you can disable the progress bar on the CLI with —np to help

**Comment by ripienaar** [comment]
merged this one, did the color fixes you should already be in a much better place I hope, lets see what else crawls out, feel free to just tag these things on #281

**Pull request merged**
