### PR TITLE
Fix build dependencies for Debian Bullseye

### PR DESCRIPTION
**Pull request by fklajn**
Signed-off-by: Franciszek Klajn <fklajn@opera.com>

### CODE REVIEW

**Comment by ripienaar** [comment]
Seems ok but really only one way to know

https://github.com/choria-io/go-choria/blob/d2bc0b87874afd175e3a674cd14a99c02e9fb98e/.circleci/config.yml#L332-L376

Add it there so we get nightly builds for bullseye.

You can axe the build_el7_ppc64le_rpms, build_el8_ppc64le_rpms and build_windows_64bit_msi out of that list

**Comment by ripienaar** [comment]
I removed the unwanted nightlies in https://github.com/choria-io/go-choria/pull/1389

**Comment by ripienaar** [comment]
thank you, I'll add them to nightly to test I guess.

**Comment by ripienaar** [comment]
OK after many annoying things we have a nightly to test, please let me know if this works, I have some work to do on moving the package repos will then do a release soon with bullseye supported

https://choria-packages-ams.ams3.digitaloceanspaces.com/nightly/bullseye_64/choria_0.99.0.20210916_amd64.deb

**Comment by fklajn** [comment]
Looks good to me:
```
[am4] [root@hmat-lx01.am4.osa ~]# lsb_release -a                                                                                                   
No LSB modules are available.                                                                                                                      
Distributor ID: Debian                                                                                                                             
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
[am4] [root@hmat-lx01.am4.osa ~]# dpkg -i choria_0.99.0.20210916_amd64.deb 
(Reading database ... 72529 files and directories currently installed.)
Preparing to unpack choria_0.99.0.20210916_amd64.deb ...
Unpacking choria (0.99.0.20210916) over (0.23.0) ...
Setting up choria (0.99.0.20210916) ...
Warning: The unit file, source configuration file or drop-ins of choria-server.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[am4] [root@hmat-lx01.am4.osa ~]# systemctl daemon-reload
[am4] [root@hmat-lx01.am4.osa ~]# systemctl restart choria-server
[am4] [root@hmat-lx01.am4.osa ~]# systemctl status choria-server
● choria-server.service - The Choria Orchestrator Server
     Loaded: loaded (/lib/systemd/system/choria-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-09-16 08:54:32 UTC; 4s ago
   Main PID: 9383 (choria)
      Tasks: 8 (limit: 2356)
     Memory: 10.7M
     CGroup: /system.slice/choria-server.service
             └─9383 /usr/bin/choria server --config=/etc/choria/server.conf
   
Sep 16 08:54:32 hmat-lx01 systemd[1]: Started The Choria Orchestrator Server.
```
Ping response:
```
[fklajn@puppet ~]$ mco ping -F 'fqdn=hmat-lx01.am4.osa'
hmat-lx01.am4.osa                        time=54.78 ms


---- ping statistics ----
1 replies max: 54.78 min: 54.78 avg: 54.78
```

**Pull request merged**
