### PR TITLE
(#2186) Build for Ubuntu Noble

### PR DESCRIPTION
**Pull request by timdeluxe**
Fixes https://github.com/choria-io/go-choria/issues/2186

### CODE REVIEW

**Comment by ripienaar** [comment]
Thanks @timdeluxe, sorry to be a pain but is it possible to sign the commits ?

**Comment by timdeluxe** [comment]
@ripienaar Sorry never did that so far, you are talking about this signing, correct? https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by ripienaar** [comment]
@timdeluxe yup, that one

**Comment by timdeluxe** [comment]
@ripienaar Took me a while, sorry, but now the commit is signed.

**Comment by ripienaar** [comment]
Thanks @timdeluxe, there's an important nats fix inbound so will probably do release again then so hopefully soon

**Comment by timdeluxe** [comment]
@ripienaar Thanks. Will the Ubuntu 24 packages released independently of a new choria puppet module release? I guess so together with your planned nats fix, right?

**Comment by ripienaar** [comment]
Yeah once the choria package is good o will do those modules

**Pull request merged**
