### PR TITLE
(#1277) Support PKCS8 containers

### PR DESCRIPTION
**Pull request by vjanelle**

### CODE REVIEW

**Comment by vjanelle** [comment]
Also need to figure out how to make a pkcs8 key too.  Woo.

**Review by smortex — APPROVED** [review]

**Comment by vjanelle** [comment]
Apparently "openssl pkcs8" was the answer to that one.

**Comment by vjanelle** [comment]
@smortex @ripienaar I think this is as good as it's going to get for RSA support.  I've got another branch with ecdsa/ed25519 support, but that's trickier - the methods aren't the same, in particular for signature validation.

**Comment by ripienaar** [comment]
nice, lgtm. Where do we come across pkc8 keys in the wild?

**Comment by vjanelle** [comment]
@ripienaar Probably only within my testing harness at work.

**Comment by vjanelle** [comment]
@ripienaar would also be important as a step to allowing things other than RSA keys.

**Pull request merged**
