### PR TITLE
(#2037) Trim space when parsing kv machine data

### PR DESCRIPTION
**Pull request by jeffmccune**
Problem:
The KV watcher stores the value from the bucket into machine data as a string instead of a JSON object when the value contains a trailing newline.  When this happens, the plugins watcher fails with `Managing plugins failed: '' expected a map, got 'string'" component=machine`

Solution:
Ignore leading and trailing white space from the watched value when the kv watcher checks the data for `{...}` or `[...]`.

Result:
The following command, which adds a trailing newline, is deserialized into machine data as a map value instead of a string value.  The plugins watcher works successfully.

```
choria machine plugins pack plugins.json plugins.seed | choria kv put PLUGINS machines -
```

Resolves: #2037

### CODE REVIEW

**Comment by jeffmccune** [comment]
@ripienaar Tossed this draft up so you could take a peek if I'm on the right path with the mocking.  I followed the examples in the existing agents.

From a design perspective, I plan to create a slice or something to find the start and end non-whitespace characters.  I get the sense you looked at the start and end to avoid the cost of trying to parse the whole byte array blindly.

**Review by ripienaar — APPROVED** [review]
Looks great, thank you.  Let me know if you're 100% on this PR and I can merge

**Comment by jeffmccune** [comment]
Yes I’m 100% done with it. Thanks for taking a look.

**Comment by ripienaar** [comment]
@jeffmccune mind signing your commit?

**Comment by jeffmccune** [comment]
Don’t mind, one min.

**Comment by jeffmccune** [comment]
Signature added.

**Pull request merged**
